### ISSUE TITLE
README on cocoapods.org isn't updated.

### ISSUE THREAD

**Issue by ahmedalmoraly** [CocoaPods/cocoadocs.org#557]
I noticed that my pod page isn't updated after pushing a new version
https://cocoapods.org/pods/AffdexSDK-iOS

It's a binary pod and the README file is at the root of the zip.

I tried `curl http://199.19.84.242:4567/redeploy/[MyPod]/latest` and it gives me `{"parsing":true}`

**Comment by mayankk2308** [comment]
Exactly the case for my pod as well.

**Comment by orta** [comment]
Looks like the CocoaPods server has completely ran out of disk space, so cloning new repos isn't working - I've started looking at deleting things but it won't be instant

**Comment by ChengappaMoEngage** [comment]
I noticed the same with my pod page too --> https://cocoapods.org/pods/MoEngage-iOS-SDK

**Comment by gregbrownlumira** [comment]
Not sure if it is related, but I also noticed that api.cocoadocs.org (referred to in the issue template) is no longer available.

**Comment by orta** [comment]
These are all fixed also, I ran through the new instructions (after bringing the server back up) in #561

**Comment by mayankk2308** [comment]
Don’t see the updated readme and change log for my pod still.

**Comment by orta** [comment]
Did you run through the recommendations in #561? I don't know what pod your talking about, so I couldn't do it myself.

**Comment by mayankk2308** [comment]
The pod is: [MKDataDetector](https://cocoapods.org/pods/MKDataDetector).

I believe I have tried the recommendations. The `curl` command does return `{"parsing": true}` as mentioned before.

**Comment by mayankk2308** [comment]
The **Overview** section is showing the **Changelog** as of now. Hopefully that's fixed soon. Thank you for all your effort so far @orta! Much appreciated.

**Comment by ChengappaMoEngage** [comment]
@orta Same for my Pod [MoEngage-iOS-SDK](https://cocoapods.org/pods/MoEngage-iOS-SDK), I see ChangeLogs in Overview and when I click on ChangeLogs it's empty.

**Comment by orta** [comment]
Cool - fixed by #563 you can re-request and it'll get fixed 👍

**Comment by Palleas** [comment]
That’s probably our fault since we got the DNS, I’ll investigate and get back to you. Sorry this migration is taking longer than expected.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kizitonwose** [comment]
@orta I'm facing this same issue with my pod [CountryPickerView](http://cocoapods.org/pods/CountryPickerView) 

I've tried `curl http://199.19.84.242:4567/redeploy/CountryPickerView/latest` but it just times out.

**Comment by Edudjr** [comment]
The same as @kizitonwose here! My pod [TLCustomMask](https://cocoapods.org/pods/TLCustomMask) was updated a month ago but no updates on cocoapods.

**Comment by LittleGreenViper** [comment]
I'm having the same problem (now) with [BMLTiOSLib](https://cocoapods.org/pods/BMLTiOSLib). The code installed in the pod update is also one version behind the head (but after the version in the README, which is VERY old).

**Comment by Palleas** [comment]
Hi there. 

You can use the following url: `https://cocoadocs.buddybuild.com/redeploy/CountryPickerView/latest`. I'm assuming it's failing because of a swift version issue, I'm happy to say I got news from our devops team that this should be fixed soon. 

As for the issue template, it's available here: https://github.com/CocoaPods/cocoadocs.org/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by gilbertchoy** [comment]
Hi @orta I'm having the same issue where changelog is not being updated.  My pod is:
https://cocoapods.org/pods/VungleSDK-iOS#changelog

I've been trying for a few days now and always getting errors:
curl http://199.19.84.242:4567/redeploy/VungleSDK-iOS/latest
curl: (7) Failed to connect to 199.19.84.242 port 4567: Operation timed out

curl https://cocoadocs.buddybuild.com/redeploy/VungleSDK-iOS/latest
Too Many Requests

curl http://api.cocoadocs.org:4567/docsets/VungleSDK-iOS/latest
curl: (6) Couldn't resolve host 'api.cocoadocs.org'

Please help.

Thanks,
Gilbert

**Comment by LittleGreenViper** [comment]
Hi Gilbert, Orta was able to direct me to [a new copy of the template](https://github.com/CocoaPods/cocoadocs.org/blob/master/.github/ISSUE_TEMPLATE.md), which has the new cURL command:

`curl http://207.254.41.223:4567/redeploy/[My Pod]/latest`

That worked for me.

**Comment by gilbertchoy** [comment]
It still doesn't refresh for me.  I tried the link:
curl http://207.254.41.223:4567/redeploy/VungleSDK-iOS/latest
{"parsing":true}

I got the correct response, but still no update after about 30 mins.

Please help!  Thanks!

**Comment by LittleGreenViper** [comment]
Wish I could be of more help. From what I can see, everything is set up OK. I have no idea why it's not working.

**Comment by kizitonwose** [comment]
@LittleGreenViper Thanks a lot, [your suggestion](https://github.com/CocoaPods/cocoadocs.org/issues/557#issuecomment-352905612) worked for me. But there's still a slight problem. The `curl` command only updates up to the last release(tag) on the repository. So, if you have modified your README after your last release, it does not update the changes after the last release. 

I also believe this is the issue @gilbertchoy is experiencing. I just checked the GitHub repo for their pod and the master is currently 6 commits ahead of the last release(tag), hence the `curl` command does not update anything after the last release.

**Comment by LittleGreenViper** [comment]
@kizitonwose That’s a feature; not a bug.

Cocoapods works on tags (set in the podspec) and whatever version was last pushed to trunk.

**Comment by kizitonwose** [comment]
@LittleGreenViper I thought as much. Thanks for helping out.
